#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-zstandard
Version  : 0.16.0
Release  : 26
URL      : https://github.com/indygreg/python-zstandard/archive/0.16.0/python-zstandard-0.16.0.tar.gz
Source0  : https://github.com/indygreg/python-zstandard/archive/0.16.0/python-zstandard-0.16.0.tar.gz
Summary  : Zstandard bindings for Python
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: python-zstandard-license = %{version}-%{release}
Requires: python-zstandard-python = %{version}-%{release}
Requires: python-zstandard-python3 = %{version}-%{release}
Requires: atomicwrites
Requires: attrs
Requires: certifi
Requires: cffi
Requires: colorama
Requires: execnet
Requires: iniconfig
Requires: mypy
Requires: packaging
Requires: pycparser
Requires: pyparsing
Requires: sortedcontainers
Requires: toml
Requires: zipp
BuildRequires : atomicwrites
BuildRequires : attrs
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : cffi
BuildRequires : colorama
BuildRequires : execnet
BuildRequires : hypothesis-python
BuildRequires : iniconfig
BuildRequires : mypy
BuildRequires : packaging
BuildRequires : pycparser
BuildRequires : pyparsing
BuildRequires : sortedcontainers
BuildRequires : toml
BuildRequires : zipp

%description
================
python-zstandard
================
| |ci-test| |ci-wheel| |ci-typing| |ci-sdist| |ci-anaconda| |ci-sphinx|

%package license
Summary: license components for the python-zstandard package.
Group: Default

%description license
license components for the python-zstandard package.


%package python
Summary: python components for the python-zstandard package.
Group: Default
Requires: python-zstandard-python3 = %{version}-%{release}

%description python
python components for the python-zstandard package.


%package python3
Summary: python3 components for the python-zstandard package.
Group: Default
Requires: python3-core
Provides: pypi(zstandard)

%description python3
python3 components for the python-zstandard package.


%prep
%setup -q -n python-zstandard-0.16.0
cd %{_builddir}/python-zstandard-0.16.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1635520314
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-zstandard
cp %{_builddir}/python-zstandard-0.16.0/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/bdfd20ae0e3f88b5609da6191fbb89f33933d948
cp %{_builddir}/python-zstandard-0.16.0/zstd/COPYING %{buildroot}/usr/share/package-licenses/python-zstandard/1d8c93712cbc9117a9e55a7ff86cebd066c8bfd8
cp %{_builddir}/python-zstandard-0.16.0/zstd/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/c4130945ca3d1f8ea4a3e8af36d3c18b2232116c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-zstandard/1d8c93712cbc9117a9e55a7ff86cebd066c8bfd8
/usr/share/package-licenses/python-zstandard/bdfd20ae0e3f88b5609da6191fbb89f33933d948
/usr/share/package-licenses/python-zstandard/c4130945ca3d1f8ea4a3e8af36d3c18b2232116c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
