#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v3
# autospec commit: 750e50d
#
Name     : python-zstandard
Version  : 0.22.0
Release  : 40
URL      : https://github.com/indygreg/python-zstandard/archive/0.22.0/python-zstandard-0.22.0.tar.gz
Source0  : https://github.com/indygreg/python-zstandard/archive/0.22.0/python-zstandard-0.22.0.tar.gz
Source1  : http://localhost/cgit/vendor/python-zstandard/snapshot/python-zstandard-2023-11-02-14-51-57.tar.xz
Summary  : Zstandard bindings for Python
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 MIT Unicode-DFS-2016
Requires: python-zstandard-license = %{version}-%{release}
Requires: python-zstandard-python = %{version}-%{release}
Requires: python-zstandard-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(atomicwrites)
BuildRequires : pypi(attrs)
BuildRequires : pypi(bashlex)
BuildRequires : pypi(bracex)
BuildRequires : pypi(certifi)
BuildRequires : pypi(cffi)
BuildRequires : pypi(cibuildwheel)
BuildRequires : pypi(colorama)
BuildRequires : pypi(exceptiongroup)
BuildRequires : pypi(execnet)
BuildRequires : pypi(filelock)
BuildRequires : pypi(hypothesis)
BuildRequires : pypi(iniconfig)
BuildRequires : pypi(mypy)
BuildRequires : pypi(mypy_extensions)
BuildRequires : pypi(packaging)
BuildRequires : pypi(platformdirs)
BuildRequires : pypi(pluggy)
BuildRequires : pypi(pycparser)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(sortedcontainers)
BuildRequires : pypi(tomli)
BuildRequires : pypi(typing_extensions)
BuildRequires : pypi(wheel)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
================
python-zstandard
================
| |ci-test| |ci-wheel| |ci-typing| |ci-sdist| |ci-anaconda| |ci-sphinx|

%package license
Summary: license components for the python-zstandard package.
Group: Default

%description license
license components for the python-zstandard package.


%package python
Summary: python components for the python-zstandard package.
Group: Default
Requires: python-zstandard-python3 = %{version}-%{release}

%description python
python components for the python-zstandard package.


%package python3
Summary: python3 components for the python-zstandard package.
Group: Default
Requires: python3-core
Provides: pypi(zstandard)
Requires: pypi(atomicwrites)
Requires: pypi(attrs)
Requires: pypi(bashlex)
Requires: pypi(bracex)
Requires: pypi(certifi)
Requires: pypi(cibuildwheel)
Requires: pypi(colorama)
Requires: pypi(exceptiongroup)
Requires: pypi(execnet)
Requires: pypi(filelock)
Requires: pypi(hypothesis)
Requires: pypi(iniconfig)
Requires: pypi(mypy)
Requires: pypi(mypy_extensions)
Requires: pypi(packaging)
Requires: pypi(platformdirs)
Requires: pypi(pluggy)
Requires: pypi(pycparser)
Requires: pypi(sortedcontainers)
Requires: pypi(tomli)
Requires: pypi(typing_extensions)

%description python3
python3 components for the python-zstandard package.


%prep
%setup -q -n python-zstandard-0.22.0
cd %{_builddir}
tar xf %{_sourcedir}/python-zstandard-2023-11-02-14-51-57.tar.xz
cd %{_builddir}/python-zstandard-0.22.0
mkdir -p ./vendor
cp -r %{_builddir}/python-zstandard-2023-11-02-14-51-57/* %{_builddir}/python-zstandard-0.22.0/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml
pushd ..
cp -a python-zstandard-0.22.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707099421
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-zstandard
cp %{_builddir}/python-zstandard-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/bdfd20ae0e3f88b5609da6191fbb89f33933d948 || :
cp %{_builddir}/python-zstandard-%{version}/zstd/COPYING %{buildroot}/usr/share/package-licenses/python-zstandard/1d8c93712cbc9117a9e55a7ff86cebd066c8bfd8 || :
cp %{_builddir}/python-zstandard-%{version}/zstd/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/d5e630eee1d3500039f2e16bed21d0f0cd580994 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/crossbeam-channel/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/crossbeam-channel/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/crossbeam-deque/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/crossbeam-deque/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/crossbeam-epoch/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/crossbeam-epoch/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/either/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/either/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/hermit-abi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/hermit-abi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/jobserver/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/jobserver/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/num_cpus/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/num_cpus/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/pkg-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/pkg-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/pyo3-build-config/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/pyo3-macros-backend/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/pyo3-macros/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/pyo3/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/rayon-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/rayon-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/rayon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/rayon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/python-zstandard/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/python-zstandard/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/python-zstandard/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/python-zstandard/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/python-zstandard/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/python-zstandard/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/python-zstandard/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/python-zstandard/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/python-zstandard/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/python-zstandard/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/python-zstandard/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/zstd-safe/LICENSE.Apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/zstd-safe/LICENSE.Mit %{buildroot}/usr/share/package-licenses/python-zstandard/7ed72f0e5fc0e0a58f758f7ac73425dc073732c7 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/zstd-sys/LICENSE.Apache-2.0 %{buildroot}/usr/share/package-licenses/python-zstandard/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/zstd-sys/LICENSE.BSD-3-Clause %{buildroot}/usr/share/package-licenses/python-zstandard/28179ca174aa05f0650753d07751af071cf5ec61 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/zstd-sys/LICENSE.Mit %{buildroot}/usr/share/package-licenses/python-zstandard/7ed72f0e5fc0e0a58f758f7ac73425dc073732c7 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/zstd-sys/zstd/COPYING %{buildroot}/usr/share/package-licenses/python-zstandard/1d8c93712cbc9117a9e55a7ff86cebd066c8bfd8 || :
cp %{_builddir}/python-zstandard-2023-11-02-14-51-57/zstd-sys/zstd/LICENSE %{buildroot}/usr/share/package-licenses/python-zstandard/d5e630eee1d3500039f2e16bed21d0f0cd580994 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-zstandard/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/python-zstandard/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/python-zstandard/1d8c93712cbc9117a9e55a7ff86cebd066c8bfd8
/usr/share/package-licenses/python-zstandard/28179ca174aa05f0650753d07751af071cf5ec61
/usr/share/package-licenses/python-zstandard/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/python-zstandard/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/python-zstandard/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/python-zstandard/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/python-zstandard/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/python-zstandard/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/python-zstandard/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/python-zstandard/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/python-zstandard/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/python-zstandard/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/python-zstandard/7ed72f0e5fc0e0a58f758f7ac73425dc073732c7
/usr/share/package-licenses/python-zstandard/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/python-zstandard/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/python-zstandard/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/python-zstandard/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/python-zstandard/bdfd20ae0e3f88b5609da6191fbb89f33933d948
/usr/share/package-licenses/python-zstandard/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/python-zstandard/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/python-zstandard/d5e630eee1d3500039f2e16bed21d0f0cd580994
/usr/share/package-licenses/python-zstandard/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/python-zstandard/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563
/usr/share/package-licenses/python-zstandard/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/python-zstandard/f498d95a48889a0b1432e420e6754881eff1d593

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
